#!/usr/bin/env node

const { DoughnutResearchAgent } = require("./research-agent");
const { createEmptyPortrait } = require("./schema");
const fs = require("fs");
const path = require("path");

const USAGE = `
Doughnut Economics Research Agent
=================================
AI-powered tool to populate city portrait data with sourced indicators.

Usage:
  node cli.js <city> <state> [options]
  node cli.js --template <city> <state>    Generate empty template
  node cli.js --report <file>              Generate data quality report

Examples:
  node cli.js "Petaluma" "California"
  node cli.js "Petaluma" "California" --ring social
  node cli.js "Amsterdam" "Netherlands" --dimensions "housing,food,health"
  node cli.js "Petaluma" "California" --output data/petaluma_ca.json
  node cli.js --template "Austin" "Texas" --output data/austin_tx.json
  node cli.js --report data/petaluma_ca.json

Options:
  --ring <social|ecological|both>   Which ring to research (default: both)
  --dimensions <dim1,dim2,...>      Specific dimensions to research
  --output <file>                   Output file path (default: stdout)
  --format <json|datajs>            Output format (default: json)
  --population <pop>                Population string (e.g., "~65,000")
  --description <desc>              City description
  --parallel <n>                    Max concurrent API requests (default: 3)
  --verbose                         Show progress messages
  --model <model>                   LLM model to use (default: gpt-4o)
  --base-url <url>                  API base URL (for non-OpenAI providers)
  --api-key <key>                   API key (or set LLM_API_KEY env var)
  --template                        Generate empty template (no AI needed)
  --report <file>                   Generate data quality report from file
  --max-retries <n>                 Max retries per dimension (default: 3)

Environment Variables:
  LLM_API_KEY      API key (works with any OpenAI-compatible provider)
  LLM_BASE_URL     API base URL
  LLM_MODEL        Model name
  OPENAI_API_KEY   OpenAI API key (fallback)
  OPENAI_BASE_URL  OpenAI base URL (fallback)

Provider Examples:
  # OpenAI
  LLM_API_KEY=sk-... node cli.js "Petaluma" "California"

  # Ollama (local)
  LLM_BASE_URL=http://localhost:11434/v1 LLM_MODEL=llama3 LLM_API_KEY=ollama node cli.js "Petaluma" "California"

  # Any OpenAI-compatible API
  LLM_BASE_URL=https://your-provider.com/v1 LLM_API_KEY=... node cli.js "Petaluma" "California"
`;

function parseArgs(argv) {
    const args = { _: [] };
    for (let i = 2; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === "--help" || arg === "-h") {
            console.log(USAGE);
            process.exit(0);
        } else if (arg === "--template") {
            args.template = true;
        } else if (arg === "--verbose") {
            args.verbose = true;
        } else if (arg.startsWith("--")) {
            const key = arg.slice(2);
            const val = argv[++i];
            args[key] = val;
        } else {
            args._.push(arg);
        }
    }
    return args;
}

function toDataJS(portrait) {
    const key = portrait.meta
        ? portrait.meta.id
        : portrait.name.toLowerCase().replace(/[^a-z0-9]+/g, "_");

    return `// Generated by doughnut-research-agent
// Run: node cli.js "${portrait.meta?.name || portrait.name}" --format datajs
// Date: ${new Date().toISOString().split("T")[0]}
// Model: ${process.env.LLM_MODEL || "gpt-4o"}

const JURISDICTIONS = {
    "${key}": ${JSON.stringify(portrait, null, 4)}
};
`;
}

async function runReport(filePath) {
    const raw = fs.readFileSync(path.resolve(filePath), 'utf8');
    const portrait = JSON.parse(raw);

    // Instantiate agent just for report generation (no API key needed)
    const agent = new (require("./research-agent").DoughnutResearchAgent)({ apiKey: 'unused' });
    const report = agent.generateReport(portrait);

    console.log("\n📊 Data Quality Report");
    console.log("=".repeat(50));
    console.log(`City: ${portrait.meta?.name || portrait.name || 'Unknown'}`);
    console.log(`Total dimensions: ${report.total}`);
    console.log(`\nConfidence: ${report.confidence.high} high, ${report.confidence.medium} medium, ${report.confidence.low} low`);
    console.log(`Errors: ${report.errors}`);
    console.log(`City-level data: ${report.cityLevelData}/${report.total}`);
    console.log(`Missing levels: ${report.missingLevels}`);
    console.log("\nDimension Details:");
    console.log("-".repeat(80));
    console.log(`${"Dimension".padEnd(28)} ${"Confidence".padEnd(12)} ${"Scale".padEnd(10)} ${"Year".padEnd(6)} Source`);
    console.log("-".repeat(80));
    report.dimensions.forEach(d => {
        const flag = d.hasError ? '❌' : d.confidence === 'high' ? '✅' : d.confidence === 'medium' ? '🟡' : '🔴';
        console.log(`${flag} ${d.name.padEnd(26)} ${(d.confidence || '?').padEnd(12)} ${(d.geographicScale || '?').padEnd(10)} ${String(d.year || '?').padEnd(6)} ${d.source || 'none'}`);
    });
}

async function main() {
    const args = parseArgs(process.argv);

    // Report mode
    if (args.report) {
        await runReport(args.report);
        return;
    }

    if (args._.length < 2) {
        console.error("Error: city and state are required.\n");
        console.log(USAGE);
        process.exit(1);
    }

    const [city, state] = args._;

    // Template mode — no AI needed
    if (args.template) {
        const id = city.toLowerCase().replace(/[^a-z0-9]+/g, '_') + '_' + state.toLowerCase().substring(0, 2);
        const portrait = createEmptyPortrait(id, city, state, "US", args.population || "Unknown", args.description || "");
        const output = args.format === 'datajs' ? toDataJS(portrait) : JSON.stringify(portrait, null, 2);

        if (args.output) {
            fs.writeFileSync(path.resolve(args.output), output);
            console.error(`Empty template written to ${args.output}`);
        } else {
            console.log(output);
        }
        return;
    }

    // Research mode — needs API key
    const apiKey = args["api-key"] || process.env.LLM_API_KEY || process.env.OPENAI_API_KEY;
    if (!apiKey) {
        console.error("Error: No API key found.");
        console.error("Set LLM_API_KEY or OPENAI_API_KEY environment variable, or pass --api-key.\n");
        console.error("Tip: Use --template to generate an empty template without an API key.");
        process.exit(1);
    }

    const agent = new (require("./research-agent").DoughnutResearchAgent)({
        apiKey,
        baseURL: args["base-url"] || process.env.LLM_BASE_URL || process.env.OPENAI_BASE_URL,
        model: args.model || process.env.LLM_MODEL,
        verbose: args.verbose,
        maxRetries: args["max-retries"] ? parseInt(args["max-retries"]) : 3,
    });

    const options = {};
    if (args.ring) options.ring = args.ring;
    if (args.dimensions) options.dimensions = args.dimensions.split(",").map(d => d.trim());
    if (args.parallel) options.parallel = parseInt(args.parallel);

    console.error(`Researching ${city}, ${state}...`);
    console.error(`Model: ${args.model || process.env.LLM_MODEL || "gpt-4o"}`);
    console.error(`Ring: ${args.ring || "both"}`);
    if (args.dimensions) console.error(`Dimensions: ${args.dimensions}`);
    console.error("");

    const portrait = await agent.buildPortrait(city, state, args.population, args.description, options);
    const format = args.format || "json";
    const output = format === "datajs" ? toDataJS(portrait) : JSON.stringify(portrait, null, 2);

    if (args.output) {
        const outPath = path.resolve(args.output);
        const dir = path.dirname(outPath);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(outPath, output);
        console.error(`\nWritten to ${outPath}`);
    } else {
        console.log(output);
    }

    // Print summary + report
    const report = agent.generateReport(portrait);
    console.error(`\n📊 Research complete for ${city}, ${state}`);
    console.error(`  Ecological: ${report.dimensions.filter(d => ECOLOGICAL_DIMENSIONS.includes(d.name)).length} dimensions`);
    console.error(`  Social:     ${report.dimensions.filter(d => SOCIAL_DIMENSIONS.includes(d.name)).length} dimensions`);
    console.error(`  Confidence: ${report.confidence.high} high, ${report.confidence.medium} medium, ${report.confidence.low} low`);
    console.error(`  City-level: ${report.cityLevelData}/${report.total}`);
    if (report.errors > 0) console.error(`  ⚠️  Errors: ${report.errors}`);
}

const { ECOLOGICAL_DIMENSIONS, SOCIAL_DIMENSIONS } = require("./schema");

main().catch(err => {
    console.error("Error:", err.message);
    if (err.stack) console.error(err.stack);
    process.exit(1);
});
